image: gradle:4.10-jdk

pipelines:
  tags:
    '*':
      - step:
          name: Deploy JAR
          script:
            - gradle clean compileKotlin build fatJar
            # Format the file like `torrents-search-1.0.0-20190222-215536.jar`
            - mv $(ls build/libs/*.jar) build/libs/$BITBUCKET_REPO_SLUG-$BITBUCKET_TAG-$(date +"%Y%m%d-%H%M%S").jar
            - curl -X POST "https://${ACCESS_TOKEN}@api.bitbucket.org/2.0/repositories/${BITBUCKET_REPO_OWNER}/${BITBUCKET_REPO_SLUG}/downloads" --form files=@"$(ls build/libs/$BITBUCKET_REPO_SLUG-*.jar)"
